CREATE TABLE `Lumbar_Puncture` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`lumbar_puncture_date` date default NULL,
`checklist_0_yes_or_no` enum('yes','no') default NULL,
`checklist_1_yes_or_no` enum('yes','no') default NULL,
`checklist_2_yes_or_no` enum('yes','no') default NULL,
`checklist_3_yes_or_no` enum('yes','no') default NULL,
`checklist_4_yes_or_no` enum('yes','no') default NULL,
`checklist_5_yes_or_no` enum('yes','no') default NULL,
`checklist_6_yes_or_no` enum('yes','no') default NULL,
`bp` varchar(255) default NULL,
`cf` varchar(255) default NULL,
`blood_sample_collected_glucose_protein` enum('yes','no') default NULL,
`clinical_history_migraines_headaches` enum('yes','no') default NULL,
`procedures_0_yes_or_no` enum('yes','no') default NULL,
`procedures_1_yes_or_no` enum('yes','no') default NULL,
`procedures_2_yes_or_no` enum('yes','no') default NULL,
`procedures_3_yes_or_no` enum('yes','no') default NULL,
`procedures_4_yes_or_no` enum('yes','no') default NULL,
`procedures_5_yes_or_no` enum('yes','no') default NULL,
`procedures_6_yes_or_no` enum('yes','no') default NULL,
`procedures_7_yes_or_no` enum('yes','no') default NULL,
`procedures_8_yes_or_no` enum('yes','no') default NULL,
`opening_pressure_mm` varchar(255) default NULL,
`sampling_time` varchar(255) default NULL,
`tube_0_volume` varchar(255) default NULL,
`tube_1_volume` varchar(255) default NULL,
`tube_2_volume` varchar(255) default NULL,
`tube_3_volume` varchar(255) default NULL,
`tube_4_volume` varchar(255) default NULL,
`wash_of_antiseptics` enum('yes','no') default NULL,
`complication_0_yes_or_no` enum('yes','no') default NULL,
`complication_1_yes_or_no` enum('yes','no') default NULL,
`complication_2_yes_or_no` enum('yes','no') default NULL,
`post_lumbar_puncture_care_0_yes_or_no` enum('yes','no') default NULL,
`post_lumbar_puncture_care_1_yes_or_no` enum('yes','no') default NULL,
`post_lumbar_puncture_care_2_yes_or_no` enum('yes','no') default NULL,
PRIMARY KEY  (`CommentID`)

              );
