CREATE TABLE `MBIC` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`total_score` varchar(255) default NULL,
`interest_motivation_drive_0_yes_or_no` enum('yes','no') default NULL,
`interest_motivation_drive_0_severity` enum('1','2','3') default NULL,
`interest_motivation_drive_1_yes_or_no` enum('yes','no') default NULL,
`interest_motivation_drive_1_severity` enum('1','2','3') default NULL,
`interest_motivation_drive_2_yes_or_no` enum('yes','no') default NULL,
`interest_motivation_drive_2_severity` enum('1','2','3') default NULL,
`interest_motivation_drive_3_yes_or_no` enum('yes','no') default NULL,
`interest_motivation_drive_3_severity` enum('1','2','3') default NULL,
`interest_motivation_drive_4_yes_or_no` enum('yes','no') default NULL,
`interest_motivation_drive_4_severity` enum('1','2','3') default NULL,
`interest_motivation_drive_5_yes_or_no` enum('yes','no') default NULL,
`interest_motivation_drive_5_severity` enum('1','2','3') default NULL,
`mood_anxiety_0_yes_or_no` enum('yes','no') default NULL,
`mood_anxiety_0_severity` enum('1','2','3') default NULL,
`mood_anxiety_1_yes_or_no` enum('yes','no') default NULL,
`mood_anxiety_1_severity` enum('1','2','3') default NULL,
`mood_anxiety_2_yes_or_no` enum('yes','no') default NULL,
`mood_anxiety_2_severity` enum('1','2','3') default NULL,
`mood_anxiety_3_yes_or_no` enum('yes','no') default NULL,
`mood_anxiety_3_severity` enum('1','2','3') default NULL,
`mood_anxiety_4_yes_or_no` enum('yes','no') default NULL,
`mood_anxiety_4_severity` enum('1','2','3') default NULL,
`mood_anxiety_5_yes_or_no` enum('yes','no') default NULL,
`mood_anxiety_5_severity` enum('1','2','3') default NULL,
`delay_control_0_yes_or_no` enum('yes','no') default NULL,
`delay_control_0_severity` enum('1','2','3') default NULL,
`delay_control_1_yes_or_no` enum('yes','no') default NULL,
`delay_control_1_severity` enum('1','2','3') default NULL,
`delay_control_2_yes_or_no` enum('yes','no') default NULL,
`delay_control_2_severity` enum('1','2','3') default NULL,
`delay_control_3_yes_or_no` enum('yes','no') default NULL,
`delay_control_3_severity` enum('1','2','3') default NULL,
`delay_control_4_yes_or_no` enum('yes','no') default NULL,
`delay_control_4_severity` enum('1','2','3') default NULL,
`delay_control_5_yes_or_no` enum('yes','no') default NULL,
`delay_control_5_severity` enum('1','2','3') default NULL,
`delay_control_6_yes_or_no` enum('yes','no') default NULL,
`delay_control_6_severity` enum('1','2','3') default NULL,
`delay_control_7_yes_or_no` enum('yes','no') default NULL,
`delay_control_7_severity` enum('1','2','3') default NULL,
`delay_control_8_yes_or_no` enum('yes','no') default NULL,
`delay_control_8_severity` enum('1','2','3') default NULL,
`delay_control_9_yes_or_no` enum('yes','no') default NULL,
`delay_control_9_severity` enum('1','2','3') default NULL,
`delay_control_10_yes_or_no` enum('yes','no') default NULL,
`delay_control_10_severity` enum('1','2','3') default NULL,
`delay_control_11_yes_or_no` enum('yes','no') default NULL,
`delay_control_11_severity` enum('1','2','3') default NULL,
`societal_social_0_yes_or_no` enum('yes','no') default NULL,
`societal_social_0_severity` enum('1','2','3') default NULL,
`societal_social_1_yes_or_no` enum('yes','no') default NULL,
`societal_social_1_severity` enum('1','2','3') default NULL,
`societal_social_2_yes_or_no` enum('yes','no') default NULL,
`societal_social_2_severity` enum('1','2','3') default NULL,
`societal_social_3_yes_or_no` enum('yes','no') default NULL,
`societal_social_3_severity` enum('1','2','3') default NULL,
`societal_social_4_yes_or_no` enum('yes','no') default NULL,
`societal_social_4_severity` enum('1','2','3') default NULL,
`beliefs_sensory_0_yes_or_no` enum('yes','no') default NULL,
`beliefs_sensory_0_severity` enum('1','2','3') default NULL,
`beliefs_sensory_1_yes_or_no` enum('yes','no') default NULL,
`beliefs_sensory_1_severity` enum('1','2','3') default NULL,
`beliefs_sensory_2_yes_or_no` enum('yes','no') default NULL,
`beliefs_sensory_2_severity` enum('1','2','3') default NULL,
`beliefs_sensory_3_yes_or_no` enum('yes','no') default NULL,
`beliefs_sensory_3_severity` enum('1','2','3') default NULL,
`beliefs_sensory_4_yes_or_no` enum('yes','no') default NULL,
`beliefs_sensory_4_severity` enum('1','2','3') default NULL,
PRIMARY KEY  (`CommentID`)

              );
