CREATE TABLE `PNA_Nurse_Admin_Physical_Exam` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`EKG_done` enum('no','yes') default NULL,
`symptom_names_0` enum('mild','moderate','severe') default NULL,
`symptom_names_1` enum('mild','moderate','severe') default NULL,
`symptom_names_2` enum('mild','moderate','severe') default NULL,
`symptom_names_3` enum('mild','moderate','severe') default NULL,
`symptom_names_4` enum('mild','moderate','severe') default NULL,
`symptom_names_5` enum('mild','moderate','severe') default NULL,
`symptom_names_6` enum('mild','moderate','severe') default NULL,
`symptom_names_7` enum('mild','moderate','severe') default NULL,
`symptom_names_8` enum('mild','moderate','severe') default NULL,
`symptom_names_9` enum('mild','moderate','severe') default NULL,
`symptom_names_10` enum('mild','moderate','severe') default NULL,
`symptom_names_11` enum('mild','moderate','severe') default NULL,
`symptom_names_12` enum('mild','moderate','severe') default NULL,
`symptom_names_13` enum('mild','moderate','severe') default NULL,
`symptom_names_14` enum('mild','moderate','severe') default NULL,
`symptom_names_15` enum('mild','moderate','severe') default NULL,
`symptom_names_16` enum('mild','moderate','severe') default NULL,
`symptom_names_17` enum('mild','moderate','severe') default NULL,
`symptom_names_18` enum('mild','moderate','severe') default NULL,
`symptom_names_19` enum('mild','moderate','severe') default NULL,
`symptom_names_20` enum('mild','moderate','severe') default NULL,
`symptom_names_21` enum('mild','moderate','severe') default NULL,
`symptom_names_22` enum('mild','moderate','severe') default NULL,
`symptom_names_23` enum('mild','moderate','severe') default NULL,
`symptom_names_24` enum('mild','moderate','severe') default NULL,
`symptom_names_25` enum('mild','moderate','severe') default NULL,
`symptom_names_26` enum('mild','moderate','severe') default NULL,
`symptom_names_27` enum('mild','moderate','severe') default NULL,
`symptom_names_28` enum('mild','moderate','severe') default NULL,
`symptom_names_29` enum('mild','moderate','severe') default NULL,
`symptom_names_30` enum('mild','moderate','severe') default NULL,
`symptom_names_31` enum('mild','moderate','severe') default NULL,
`symptom_names_32` enum('mild','moderate','severe') default NULL,
`symptom_names_33` enum('mild','moderate','severe') default NULL,
`symptom_names_34` enum('mild','moderate','severe') default NULL,
`symptom_names_35` enum('mild','moderate','severe') default NULL,
`symptom_names_36` enum('mild','moderate','severe') default NULL,
`symptom_names_37` enum('mild','moderate','severe') default NULL,
`symptom_names_38` enum('mild','moderate','severe') default NULL,
`symptom_names_39` enum('mild','moderate','severe') default NULL,
`symptom_names_40` enum('mild','moderate','severe') default NULL,
`symptom_names_41` enum('mild','moderate','severe') default NULL,
`symptom_names_42` enum('mild','moderate','severe') default NULL,
`symptom_names_2_43_label` varchar(255) default NULL,
`symptom_names_2_43_severity` enum('mild','moderate','severe') default NULL,
`symptom_names_2_44_label` varchar(255) default NULL,
`symptom_names_2_44_severity` enum('mild','moderate','severe') default NULL,
`PE_done` enum('no','yes') default NULL,
`PE_no` varchar(255) default NULL,
`PE_no_status` enum('not_answered') default NULL,
`PE_yes` varchar(255) default NULL,
`PE_yes_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              );
