CREATE TABLE `Screening_General_Exclusion_Criteria` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`exclusion_criteria_group_1_0_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_1_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_2_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_3_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_4_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_5_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_6_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_7_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_8_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_9_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_10_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_11_yes_or_no` enum('no','yes') default NULL,
`exclusion_criteria_group_1_12_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_0_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_1_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_2_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_3_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_4_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_5_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_6_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_7_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_8_yes_or_no` enum('no','yes') default NULL,
`abnormality_disease_9_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_0_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_1_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_2_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_3_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_4_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_5_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_6_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_mri_7_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_pet_0_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_pet_1_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_l_p_0_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_l_p_1_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_l_p_2_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_l_p_3_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_l_p_4_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_l_p_5_yes_or_no` enum('no','yes') default NULL,
`contraindications_to_l_p_6_yes_or_no` enum('no','yes') default NULL,
PRIMARY KEY  (`CommentID`)

              );
